version: '3'

networks:
  chudo-koni-network:

services:

  # nginx
  nginx-service:
    image: nginx:1.23.1
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./../server:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.1-service
      - postgres-service
    networks:
      - chudo-koni-network

  # php
  php8.1-service:
    build:
      context: ./../server
      dockerfile: ./../docker/php/Dockerfile
    container_name: php8.1-container
    ports:
      - "9000:9000"
    volumes:
      - ./../server:/var/www/project
    networks:
      - chudo-koni-network

  # postgres
  postgres-service:
    image: postgres:14.5
    container_name: postgres-container
    ports:
      - "6432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    networks:
      - chudo-koni-network

  # node
  node-service:
    build:
      context: ./../client
      dockerfile: ./../docker/node/Dockerfile
    container_name: node-container
    volumes:
      - ./../client:/var/www/project
    ports:
      - "8090:3000"
    networks:
      - chudo-koni-network